<?php

namespace Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Repository;

use Datasus\Sisvs\Base\BaseBundle\Repository\BaseRepository;

/**
 * ModalidadeApresentacaoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ModalidadeApresentacaoRepository extends BaseRepository
{
			/**
			 * @função updateModalidadeApresentacao serve para atualizar a ordem das apresentações
			 * @param $dados
			 * @return mixed
			 */
			public function updateModalidadeApresentacao($coModalidade, $coApresentacao, $nuOrdem)
			{
					$entidade = $this->getEntityManager()->createQueryBuilder();
					$query    = $entidade->update($this->getEntityName(), 'i')
							->set('i.nuOrdem', '?1')
							->where('i.coModalidade = ?2')
							->andWhere('i.coApresentacao = ?3')
							->setParameter(1, $nuOrdem)
							->setParameter(2, $coModalidade)
							->setParameter(3, $coApresentacao)
							->getQuery();
					return $query->execute();
			}
}
