<?php

namespace Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Repository;

use Datasus\Sisvs\Base\BaseBundle\Repository\BaseRepository;
use Symfony\Component\HttpFoundation\Request;

/**
 * TipoModalidadeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TipoModalidadeRepository extends BaseRepository
{
		public function listaTipoModalidade(Request $request)
		{
				$params = array();
				parse_str($request->query->get('data'), $params);

				$query = $this
						->getEntityManager()
						->createQueryBuilder()
						->select('e')
						->from($this->getEntityName(), 'e');

				if ($params['stAtivo'] == '' and $params['noTipoModalidade'] == '') {
						$query->andWhere($query->expr()->eq("e.stAtivo", ":stAtivo"))
								->setParameter('stAtivo', 'S');
				}
				if ($params['stAtivo'] != null) {
						$query->andWhere($query->expr()->eq("e.stAtivo", ":stAtivo"))
								->setParameter('stAtivo', $params['stAtivo']);
				}

				if (isset($params['noTipoModalidade']) and $params['noTipoModalidade']) {
						$query->andWhere($query->expr()->like("UPPER(e.noTipoModalidade)", "UPPER(:noTipoModalidade)"))
								->setParameter('noTipoModalidade', '%' . $params['noTipoModalidade'] . '%');
				}
               $this->addOrderBy($query,$request);
				return $query
						->getQuery()
						->getArrayResult();
		}

}
