parameters:
#    datasus_core_base.example.class: Datasus\Core\BaseBundle\Example

services:
#    datasus_core_base.example:
#        class: %datasus_core_base.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
