<?php

namespace Datasus\Sisvs\ExpoEpi\FormularioBundle\Repository;

use Datasus\Sisvs\Base\BaseBundle\Repository\BaseRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Tests\ORM\Functional\DatabaseDriverTest;
use Symfony\Component\HttpFoundation\Request;


/**
 * SituacaoFormularioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SituacaoFormularioRepository extends BaseRepository
{
		public function getSituacaoFormulario($tipoFormulario = null){
				$query = $this->getEntityManager()
						->createQueryBuilder()
						->select('s')
						->from($this->_entityName, 's');
				if($tipoFormulario){
						$query->andWhere('s.coSituacaoFormulario = :coSituacaoFormulario')
								->setParameter('coSituacaoFormulario',$tipoFormulario);
				}
				return $query->getQuery()->getSingleResult();
		}
}