<?php

namespace Proxies\__CG__\Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class TemaEntity extends \Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Entity\TemaEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'coSeqTema', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'coArea', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'coTipoClassificacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'noTema', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'dsTema', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'nuTema', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'stAtivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'coInscricao');
        }

        return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'coSeqTema', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'coArea', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'coTipoClassificacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'noTema', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'dsTema', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'nuTema', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'stAtivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\TemaEntity' . "\0" . 'coInscricao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (TemaEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoSeqTema()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoSeqTema();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoSeqTema', array());

        return parent::getCoSeqTema();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoSeqTema($coSeqTema)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoSeqTema', array($coSeqTema));

        return parent::setCoSeqTema($coSeqTema);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoTema()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoTema', array());

        return parent::getNoTema();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoTema($noTema)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoTema', array($noTema));

        return parent::setNoTema($noTema);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsTema()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsTema', array());

        return parent::getDsTema();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsTema($dsTema)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsTema', array($dsTema));

        return parent::setDsTema($dsTema);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoArea', array());

        return parent::getCoArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoArea($coArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoArea', array($coArea));

        return parent::setCoArea($coArea);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoTipoClassificacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoTipoClassificacao', array());

        return parent::getCoTipoClassificacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoTipoClassificacao($coTipoClassificacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoTipoClassificacao', array($coTipoClassificacao));

        return parent::setCoTipoClassificacao($coTipoClassificacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuTema($alfa = false)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuTema', array($alfa));

        return parent::getNuTema($alfa);
    }

    /**
     * {@inheritDoc}
     */
    public function setNuTema($nuTema)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuTema', array($nuTema));

        return parent::setNuTema($nuTema);
    }

    /**
     * {@inheritDoc}
     */
    public function getStAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAtivo', array());

        return parent::getStAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStAtivo($stAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAtivo', array($stAtivo));

        return parent::setStAtivo($stAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoInscricao', array());

        return parent::getCoInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoInscricao($coInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoInscricao', array($coInscricao));

        return parent::setCoInscricao($coInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function loadValues(\Datasus\Core\BaseBundle\Entity\AbstractBase $entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'loadValues', array($entity));

        return parent::loadValues($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function fromArray(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fromArray', array($data));

        return parent::fromArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($parent));

        return parent::toArray($parent);
    }

}
