<?php

namespace Proxies\__CG__\Datasus\Sisvs\ExpoEpi\AutorBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class AnexoEntity extends \Datasus\Sisvs\ExpoEpi\AutorBundle\Entity\AnexoEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\AnexoEntity' . "\0" . 'coSeqAnexo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\AnexoEntity' . "\0" . 'coInscricao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\AnexoEntity' . "\0" . 'noArquivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\AnexoEntity' . "\0" . 'dsArquivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\AnexoEntity' . "\0" . 'stAtivo');
        }

        return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\AnexoEntity' . "\0" . 'coSeqAnexo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\AnexoEntity' . "\0" . 'coInscricao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\AnexoEntity' . "\0" . 'noArquivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\AnexoEntity' . "\0" . 'dsArquivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\AnexoEntity' . "\0" . 'stAtivo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (AnexoEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoInscricao', array());

        return parent::getCoInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoInscricao($coInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoInscricao', array($coInscricao));

        return parent::setCoInscricao($coInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoSeqAnexo()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoSeqAnexo();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoSeqAnexo', array());

        return parent::getCoSeqAnexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoSeqAnexo($coSeqAnexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoSeqAnexo', array($coSeqAnexo));

        return parent::setCoSeqAnexo($coSeqAnexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsArquivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsArquivo', array());

        return parent::getDsArquivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsArquivo($dsArquivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsArquivo', array($dsArquivo));

        return parent::setDsArquivo($dsArquivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoArquivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoArquivo', array());

        return parent::getNoArquivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoArquivo($noArquivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoArquivo', array($noArquivo));

        return parent::setNoArquivo($noArquivo);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getStAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAtivo', array());

        return parent::getStAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStAtivo($stAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAtivo', array($stAtivo));

        return parent::setStAtivo($stAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function loadValues(\Datasus\Core\BaseBundle\Entity\AbstractBase $entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'loadValues', array($entity));

        return parent::loadValues($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function fromArray(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fromArray', array($data));

        return parent::fromArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($parent));

        return parent::toArray($parent);
    }

}
