<?php

namespace Proxies\__CG__\Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class RegiaoEntity extends \Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Entity\RegiaoEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\RegiaoEntity' . "\0" . 'coRegiao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\RegiaoEntity' . "\0" . 'noRegiao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\RegiaoEntity' . "\0" . 'sgRegiao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\RegiaoEntity' . "\0" . 'stRegistroAtivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\RegiaoEntity' . "\0" . 'coRegiaoSvs', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\RegiaoEntity' . "\0" . 'coUf');
        }

        return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\RegiaoEntity' . "\0" . 'coRegiao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\RegiaoEntity' . "\0" . 'noRegiao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\RegiaoEntity' . "\0" . 'sgRegiao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\RegiaoEntity' . "\0" . 'stRegistroAtivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\RegiaoEntity' . "\0" . 'coRegiaoSvs', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\RegiaoEntity' . "\0" . 'coUf');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (RegiaoEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoRegiao()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoRegiao();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoRegiao', array());

        return parent::getCoRegiao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoRegiao($coRegiao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoRegiao', array($coRegiao));

        return parent::setCoRegiao($coRegiao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoRegiaoSvs()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoRegiaoSvs', array());

        return parent::getCoRegiaoSvs();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoRegiaoSvs($coRegiaoSvs)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoRegiaoSvs', array($coRegiaoSvs));

        return parent::setCoRegiaoSvs($coRegiaoSvs);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoRegiao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoRegiao', array());

        return parent::getNoRegiao();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoRegiao($noRegiao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoRegiao', array($noRegiao));

        return parent::setNoRegiao($noRegiao);
    }

    /**
     * {@inheritDoc}
     */
    public function getSgRegiao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSgRegiao', array());

        return parent::getSgRegiao();
    }

    /**
     * {@inheritDoc}
     */
    public function setSgRegiao($sgRegiao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSgRegiao', array($sgRegiao));

        return parent::setSgRegiao($sgRegiao);
    }

    /**
     * {@inheritDoc}
     */
    public function getStRegistroAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStRegistroAtivo', array());

        return parent::getStRegistroAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStRegistroAtivo($stRegistroAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStRegistroAtivo', array($stRegistroAtivo));

        return parent::setStRegistroAtivo($stRegistroAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoUf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoUf', array());

        return parent::getCoUf();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoUf($coUf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoUf', array($coUf));

        return parent::setCoUf($coUf);
    }

    /**
     * {@inheritDoc}
     */
    public function loadValues(\Datasus\Core\BaseBundle\Entity\AbstractBase $entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'loadValues', array($entity));

        return parent::loadValues($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function fromArray(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fromArray', array($data));

        return parent::fromArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($parent));

        return parent::toArray($parent);
    }

}
