<?php

namespace Proxies\__CG__\Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ModalidadeEntity extends \Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Entity\ModalidadeEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coSeqModalidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coEvento', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coModalidadeApresentacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coModalidadeCriterio', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coModalidadeInstituicao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coCriterio', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'noModalidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'dsModalidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'stAtivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'stOcultaDados', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coTipoModalidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coFormularioDeInscricao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coArea', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'stPossuiOrientador', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'stExigeAnexo');
        }

        return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coSeqModalidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coEvento', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coModalidadeApresentacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coModalidadeCriterio', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coModalidadeInstituicao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coCriterio', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'noModalidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'dsModalidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'stAtivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'stOcultaDados', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coTipoModalidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coFormularioDeInscricao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'coArea', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'stPossuiOrientador', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ModalidadeEntity' . "\0" . 'stExigeAnexo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ModalidadeEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoSeqModalidade()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoSeqModalidade();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoSeqModalidade', array());

        return parent::getCoSeqModalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoSeqModalidade($coSeqModalidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoSeqModalidade', array($coSeqModalidade));

        return parent::setCoSeqModalidade($coSeqModalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoEvento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoEvento', array());

        return parent::getCoEvento();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoEvento($coEvento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoEvento', array($coEvento));

        return parent::setCoEvento($coEvento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoModalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoModalidade', array());

        return parent::getNoModalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoModalidade($noModalidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoModalidade', array($noModalidade));

        return parent::setNoModalidade($noModalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsModalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsModalidade', array());

        return parent::getDsModalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsModalidade($dsModalidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsModalidade', array($dsModalidade));

        return parent::setDsModalidade($dsModalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getStAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAtivo', array());

        return parent::getStAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStAtivo($stAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAtivo', array($stAtivo));

        return parent::setStAtivo($stAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoCriterio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoCriterio', array());

        return parent::getCoCriterio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoCriterio($coCriterio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoCriterio', array($coCriterio));

        return parent::setCoCriterio($coCriterio);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoModalidadeApresentacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoModalidadeApresentacao', array());

        return parent::getCoModalidadeApresentacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoModalidadeApresentacao($coModalidadeApresentacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoModalidadeApresentacao', array($coModalidadeApresentacao));

        return parent::setCoModalidadeApresentacao($coModalidadeApresentacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoModalidadeInstituicao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoModalidadeInstituicao', array());

        return parent::getCoModalidadeInstituicao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoModalidadeInstituicao($coModalidadeInstituicao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoModalidadeInstituicao', array($coModalidadeInstituicao));

        return parent::setCoModalidadeInstituicao($coModalidadeInstituicao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoModalidadeCriterio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoModalidadeCriterio', array());

        return parent::getCoModalidadeCriterio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoModalidadeCriterio($coModalidadeCriterio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoModalidadeCriterio', array($coModalidadeCriterio));

        return parent::setCoModalidadeCriterio($coModalidadeCriterio);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoTipoModalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoTipoModalidade', array());

        return parent::getCoTipoModalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoTipoModalidade($coTipoModalidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoTipoModalidade', array($coTipoModalidade));

        return parent::setCoTipoModalidade($coTipoModalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getStPossuiOrientador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStPossuiOrientador', array());

        return parent::getStPossuiOrientador();
    }

    /**
     * {@inheritDoc}
     */
    public function setStPossuiOrientador($stPossuiOrientador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStPossuiOrientador', array($stPossuiOrientador));

        return parent::setStPossuiOrientador($stPossuiOrientador);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoFormularioDeInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoFormularioDeInscricao', array());

        return parent::getCoFormularioDeInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoFormularioDeInscricao($coFormularioDeInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoFormularioDeInscricao', array($coFormularioDeInscricao));

        return parent::setCoFormularioDeInscricao($coFormularioDeInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoArea()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoArea', array());

        return parent::getCoArea();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoArea($coArea)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoArea', array($coArea));

        return parent::setCoArea($coArea);
    }

    /**
     * {@inheritDoc}
     */
    public function setStExigeAnexo($stExigeAnexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStExigeAnexo', array($stExigeAnexo));

        return parent::setStExigeAnexo($stExigeAnexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getStExigeAnexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStExigeAnexo', array());

        return parent::getStExigeAnexo();
    }

    /**
     * {@inheritDoc}
     */
    public function getStOcultaDados()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStOcultaDados', array());

        return parent::getStOcultaDados();
    }

    /**
     * {@inheritDoc}
     */
    public function setStOcultaDados($stOcultaDados)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStOcultaDados', array($stOcultaDados));

        return parent::setStOcultaDados($stOcultaDados);
    }

    /**
     * {@inheritDoc}
     */
    public function loadValues(\Datasus\Core\BaseBundle\Entity\AbstractBase $entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'loadValues', array($entity));

        return parent::loadValues($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function fromArray(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fromArray', array($data));

        return parent::fromArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($parent));

        return parent::toArray($parent);
    }

}
