<?php

namespace Proxies\__CG__\Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class ApresentacaoEntity extends \Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Entity\ApresentacaoEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ApresentacaoEntity' . "\0" . 'coSeqApresentacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ApresentacaoEntity' . "\0" . 'noApresentacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ApresentacaoEntity' . "\0" . 'dsApresentacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ApresentacaoEntity' . "\0" . 'stAtivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ApresentacaoEntity' . "\0" . 'coModalidadeApresentacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ApresentacaoEntity' . "\0" . 'coInscricaoApresentacao');
        }

        return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ApresentacaoEntity' . "\0" . 'coSeqApresentacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ApresentacaoEntity' . "\0" . 'noApresentacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ApresentacaoEntity' . "\0" . 'dsApresentacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ApresentacaoEntity' . "\0" . 'stAtivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ApresentacaoEntity' . "\0" . 'coModalidadeApresentacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\ApresentacaoEntity' . "\0" . 'coInscricaoApresentacao');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (ApresentacaoEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoSeqApresentacao()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoSeqApresentacao();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoSeqApresentacao', array());

        return parent::getCoSeqApresentacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoSeqApresentacao($coSeqApresentacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoSeqApresentacao', array($coSeqApresentacao));

        return parent::setCoSeqApresentacao($coSeqApresentacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoApresentacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoApresentacao', array());

        return parent::getNoApresentacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoApresentacao($noApresentacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoApresentacao', array($noApresentacao));

        return parent::setNoApresentacao($noApresentacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsApresentacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsApresentacao', array());

        return parent::getDsApresentacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsApresentacao($dsApresentacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsApresentacao', array($dsApresentacao));

        return parent::setDsApresentacao($dsApresentacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getStAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAtivo', array());

        return parent::getStAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStAtivo($stAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAtivo', array($stAtivo));

        return parent::setStAtivo($stAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCoModalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCoModalidade', array());

        return parent::getArrayCoModalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoModalidadeApresentacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoModalidadeApresentacao', array());

        return parent::getCoModalidadeApresentacao();
    }

    /**
     * {@inheritDoc}
     */
    public function getCoInscricaoApresentacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoInscricaoApresentacao', array());

        return parent::getCoInscricaoApresentacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoInscricaoApresentacao($coInscricaoApresentacao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoInscricaoApresentacao', array($coInscricaoApresentacao));

        return parent::setCoInscricaoApresentacao($coInscricaoApresentacao);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function loadValues(\Datasus\Core\BaseBundle\Entity\AbstractBase $entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'loadValues', array($entity));

        return parent::loadValues($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function fromArray(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fromArray', array($data));

        return parent::fromArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($parent));

        return parent::toArray($parent);
    }

}
