<?php

namespace Proxies\__CG__\Datasus\Sisvs\ExpoEpi\AutorBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class InscricaoEntity extends \Datasus\Sisvs\ExpoEpi\AutorBundle\Entity\InscricaoEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coSeqInscricao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'nuInscricao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coTema', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'stAutoria', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'noOrientador', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'noCoOrientador', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'dsTitulo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'dsResumo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'stVeracidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'dtVeracidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coInstituicao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coSituacaoInscricao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coHistorico', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coAnexo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coAutor', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coInscricaoApresentacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coUsuario', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'dsEmailSecundario', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'stAtivo');
        }

        return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coSeqInscricao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'nuInscricao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coTema', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'stAutoria', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'noOrientador', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'noCoOrientador', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'dsTitulo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'dsResumo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'stVeracidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'dtVeracidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coInstituicao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coSituacaoInscricao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coHistorico', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coAnexo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coAutor', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coInscricaoApresentacao', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'coUsuario', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'dsEmailSecundario', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AutorBundle\\Entity\\InscricaoEntity' . "\0" . 'stAtivo');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (InscricaoEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoAnexo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoAnexo', array());

        return parent::getCoAnexo();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoAnexo($coAnexo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoAnexo', array($coAnexo));

        return parent::setCoAnexo($coAnexo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoHistorico()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoHistorico', array());

        return parent::getCoHistorico();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoHistorico($coHistorico)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoHistorico', array($coHistorico));

        return parent::setCoHistorico($coHistorico);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoInstituicao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoInstituicao', array());

        return parent::getCoInstituicao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoInstituicao($coInstituicao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoInstituicao', array($coInstituicao));

        return parent::setCoInstituicao($coInstituicao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoSeqInscricao()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoSeqInscricao();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoSeqInscricao', array());

        return parent::getCoSeqInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoSeqInscricao($coSeqInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoSeqInscricao', array($coSeqInscricao));

        return parent::setCoSeqInscricao($coSeqInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoTema()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoTema', array());

        return parent::getCoTema();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoTema($coTema)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoTema', array($coTema));

        return parent::setCoTema($coTema);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsResumo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsResumo', array());

        return parent::getDsResumo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsResumo($dsResumo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsResumo', array($dsResumo));

        return parent::setDsResumo($dsResumo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsTitulo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsTitulo', array());

        return parent::getDsTitulo();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsTitulo($dsTitulo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsTitulo', array($dsTitulo));

        return parent::setDsTitulo($dsTitulo);
    }

    /**
     * {@inheritDoc}
     */
    public function getDtVeracidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDtVeracidade', array());

        return parent::getDtVeracidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setDtVeracidade($dtVeracidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDtVeracidade', array($dtVeracidade));

        return parent::setDtVeracidade($dtVeracidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoCoOrientador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoCoOrientador', array());

        return parent::getNoCoOrientador();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoCoOrientador($noCoOrientador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoCoOrientador', array($noCoOrientador));

        return parent::setNoCoOrientador($noCoOrientador);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoOrientador()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoOrientador', array());

        return parent::getNoOrientador();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoOrientador($noOrientador)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoOrientador', array($noOrientador));

        return parent::setNoOrientador($noOrientador);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuInscricao', array());

        return parent::getNuInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuInscricao($nuInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuInscricao', array($nuInscricao));

        return parent::setNuInscricao($nuInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getStAutoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAutoria', array());

        return parent::getStAutoria();
    }

    /**
     * {@inheritDoc}
     */
    public function setStAutoria($stAutoria)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAutoria', array($stAutoria));

        return parent::setStAutoria($stAutoria);
    }

    /**
     * {@inheritDoc}
     */
    public function getStVeracidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStVeracidade', array());

        return parent::getStVeracidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setStVeracidade($stVeracidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStVeracidade', array($stVeracidade));

        return parent::setStVeracidade($stVeracidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoSituacaoInscricao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoSituacaoInscricao', array());

        return parent::getCoSituacaoInscricao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoSituacaoInscricao($coSituacaoInscricao)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoSituacaoInscricao', array($coSituacaoInscricao));

        return parent::setCoSituacaoInscricao($coSituacaoInscricao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoAutor()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoAutor', array());

        return parent::getCoAutor();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoAutor($coAutor)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoAutor', array($coAutor));

        return parent::setCoAutor($coAutor);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoInscricaoApresentacao()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoInscricaoApresentacao', array());

        return parent::getCoInscricaoApresentacao();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoInscricaoApresentacao($coInscricaoApresentacao = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoInscricaoApresentacao', array($coInscricaoApresentacao));

        return parent::setCoInscricaoApresentacao($coInscricaoApresentacao);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoUsuario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoUsuario', array());

        return parent::getCoUsuario();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoUsuario($coUsuario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoUsuario', array($coUsuario));

        return parent::setCoUsuario($coUsuario);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsEmailSecundario()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsEmailSecundario', array());

        return parent::getDsEmailSecundario();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsEmailSecundario($dsEmailSecundario)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsEmailSecundario', array($dsEmailSecundario));

        return parent::setDsEmailSecundario($dsEmailSecundario);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getStAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAtivo', array());

        return parent::getStAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStAtivo($stAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAtivo', array($stAtivo));

        return parent::setStAtivo($stAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function loadValues(\Datasus\Core\BaseBundle\Entity\AbstractBase $entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'loadValues', array($entity));

        return parent::loadValues($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function fromArray(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fromArray', array($data));

        return parent::fromArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($parent));

        return parent::toArray($parent);
    }

}
