<?php

namespace Proxies\__CG__\Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CriterioEntity extends \Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Entity\CriterioEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CriterioEntity' . "\0" . 'coSeqCriterio', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CriterioEntity' . "\0" . 'noCriterio', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CriterioEntity' . "\0" . 'dsCriterio', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CriterioEntity' . "\0" . 'stAtivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CriterioEntity' . "\0" . 'coModalidadeCriterio');
        }

        return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CriterioEntity' . "\0" . 'coSeqCriterio', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CriterioEntity' . "\0" . 'noCriterio', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CriterioEntity' . "\0" . 'dsCriterio', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CriterioEntity' . "\0" . 'stAtivo', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CriterioEntity' . "\0" . 'coModalidadeCriterio');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CriterioEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoSeqCriterio()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoSeqCriterio();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoSeqCriterio', array());

        return parent::getCoSeqCriterio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoSeqCriterio($coSeqCriterio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoSeqCriterio', array($coSeqCriterio));

        return parent::setCoSeqCriterio($coSeqCriterio);
    }

    /**
     * {@inheritDoc}
     */
    public function getDsCriterio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsCriterio', array());

        return parent::getDsCriterio();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsCriterio($dsCriterio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsCriterio', array($dsCriterio));

        return parent::setDsCriterio($dsCriterio);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoCriterio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoCriterio', array());

        return parent::getNoCriterio();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoCriterio($noCriterio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoCriterio', array($noCriterio));

        return parent::setNoCriterio($noCriterio);
    }

    /**
     * {@inheritDoc}
     */
    public function getStAtivo()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStAtivo', array());

        return parent::getStAtivo();
    }

    /**
     * {@inheritDoc}
     */
    public function setStAtivo($stAtivo)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStAtivo', array($stAtivo));

        return parent::setStAtivo($stAtivo);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoModalidadeCriterio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoModalidadeCriterio', array());

        return parent::getCoModalidadeCriterio();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayCoModalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayCoModalidade', array());

        return parent::getArrayCoModalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayBindModalidaadeCriterioStPermiteBloqueio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayBindModalidaadeCriterioStPermiteBloqueio', array());

        return parent::getArrayBindModalidaadeCriterioStPermiteBloqueio();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayBindModalidaadeCriterioStPossuiCategoria()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayBindModalidaadeCriterioStPossuiCategoria', array());

        return parent::getArrayBindModalidaadeCriterioStPossuiCategoria();
    }

    /**
     * {@inheritDoc}
     */
    public function getArrayBindModalidaadeCriterioStNaoInformado()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArrayBindModalidaadeCriterioStNaoInformado', array());

        return parent::getArrayBindModalidaadeCriterioStNaoInformado();
    }

    /**
     * {@inheritDoc}
     */
    public function loadValues(\Datasus\Core\BaseBundle\Entity\AbstractBase $entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'loadValues', array($entity));

        return parent::loadValues($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function fromArray(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fromArray', array($data));

        return parent::fromArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($parent));

        return parent::toArray($parent);
    }

}
