<?php

namespace Proxies\__CG__\Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class CepEntity extends \Datasus\Sisvs\ExpoEpi\AdministrativoBundle\Entity\CepEntity implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'coCep', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'nuCep', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'sgUf', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'coMunicipio', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'noLocalidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'noLogradouro', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'dsComplemento');
        }

        return array('__isInitialized__', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'coCep', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'nuCep', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'sgUf', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'coMunicipio', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'noLocalidade', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'noLogradouro', '' . "\0" . 'Datasus\\Sisvs\\ExpoEpi\\AdministrativoBundle\\Entity\\CepEntity' . "\0" . 'dsComplemento');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (CepEntity $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getCoCep()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getCoCep();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoCep', array());

        return parent::getCoCep();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoCep($coCep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoCep', array($coCep));

        return parent::setCoCep($coCep);
    }

    /**
     * {@inheritDoc}
     */
    public function setCoMunicipioIbge($coMunicipioIbge)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoMunicipioIbge', array($coMunicipioIbge));

        return parent::setCoMunicipioIbge($coMunicipioIbge);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoMunicipioIbge()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoMunicipioIbge', array());

        return parent::getCoMunicipioIbge();
    }

    /**
     * {@inheritDoc}
     */
    public function getDsComplemento()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDsComplemento', array());

        return parent::getDsComplemento();
    }

    /**
     * {@inheritDoc}
     */
    public function setDsComplemento($dsComplemento)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDsComplemento', array($dsComplemento));

        return parent::setDsComplemento($dsComplemento);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoLocalidade()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoLocalidade', array());

        return parent::getNoLocalidade();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoLocalidade($noLocalidade)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoLocalidade', array($noLocalidade));

        return parent::setNoLocalidade($noLocalidade);
    }

    /**
     * {@inheritDoc}
     */
    public function getNoLogradouro()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNoLogradouro', array());

        return parent::getNoLogradouro();
    }

    /**
     * {@inheritDoc}
     */
    public function setNoLogradouro($noLogradouro)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNoLogradouro', array($noLogradouro));

        return parent::setNoLogradouro($noLogradouro);
    }

    /**
     * {@inheritDoc}
     */
    public function getNuCep()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNuCep', array());

        return parent::getNuCep();
    }

    /**
     * {@inheritDoc}
     */
    public function setNuCep($nuCep)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNuCep', array($nuCep));

        return parent::setNuCep($nuCep);
    }

    /**
     * {@inheritDoc}
     */
    public function getSgUf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getSgUf', array());

        return parent::getSgUf();
    }

    /**
     * {@inheritDoc}
     */
    public function setSgUf($sgUf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setSgUf', array($sgUf));

        return parent::setSgUf($sgUf);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoMunicipio()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoMunicipio', array());

        return parent::getCoMunicipio();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoMunicipio($coMunicipio)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoMunicipio', array($coMunicipio));

        return parent::setCoMunicipio($coMunicipio);
    }

    /**
     * {@inheritDoc}
     */
    public function loadValues(\Datasus\Core\BaseBundle\Entity\AbstractBase $entity)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'loadValues', array($entity));

        return parent::loadValues($entity);
    }

    /**
     * {@inheritDoc}
     */
    public function fromArray(array $data)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'fromArray', array($data));

        return parent::fromArray($data);
    }

    /**
     * {@inheritDoc}
     */
    public function toArray($parent = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'toArray', array($parent));

        return parent::toArray($parent);
    }

}
