################## area ##################
datasus_sisvs_expoepi_administrativo_area:
    pattern: /area
    defaults:
        _controller: DatasusSisvsExpoEpiAdministrativoBundle:Area:index
        label: "Área"
        parent: "datasus_sisvs_expoepi_administrativo_modalidade"

datasus_sisvs_expoepi_administrativo_area_search:
    pattern: /area/search
    defaults: { _controller: DatasusSisvsExpoEpiAdministrativoBundle:Area:search  }

datasus_sisvs_expoepi_administrativo_area_create:
    pattern: /area/create
    defaults:
        _controller: DatasusSisvsExpoEpiAdministrativoBundle:Area:create
        label: "Cadastrar Área"
        parent: "datasus_sisvs_expoepi_administrativo_area"

datasus_sisvs_expoepi_administrativo_area_edit:
    pattern: /area/edit
    defaults:
      _controller: DatasusSisvsExpoEpiAdministrativoBundle:Area:edit
      label: "Alterar Área"
      parent: "datasus_sisvs_expoepi_administrativo_area"

datasus_sisvs_expoepi_administrativo_area_toogle-status:
    pattern: /area/toogle-status
    defaults: { _controller: DatasusSisvsExpoEpiAdministrativoBundle:Area:toogleStatus }

datasus_sisvs_expoepi_administrativo_area_view:
    pattern: /area/view
    defaults: { _controller: DatasusSisvsExpoEpiAdministrativoBundle:Area:view }

datasus_sisvs_expoepi_administrativo_area_combo_box:
    pattern: /area/combo-box
    defaults: { _controller: DatasusSisvsExpoEpiAdministrativoBundle:Area:comboBox }