<?php

namespace Datasus\Sisvs\Base\SecurityBundle\Repository;

use Datasus\Core\BaseBundle\EntityRepository\AbstractBase;

/**
 * UsuarioRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioRepository extends AbstractBase
{
		public function findAllCoSeqUsuario($ids)
		{
				$queryBuilder = $this->getEntityManager()->createQueryBuilder();
				$query = $this
						->getEntityManager()
						->createQueryBuilder()
						->select('u')
						->from($this->getEntityName(), 'u')
						->where("u.stRegistroAtivo = :stRegistroAtivo")
						->setParameter('stRegistroAtivo', 'S');
				if (isset($ids) and $ids) {
						$query->andWhere($queryBuilder->expr()->in("u.coSeqUsuario", ":coSeqUsuario"))
								->setParameter('coSeqUsuario', $ids);
				}
				return $query->getQuery()->getArrayResult();
		}
}
