<?php

namespace Datasus\Sisvs\Base\SecurityBundle\Repository;

use Datasus\Core\BaseBundle\EntityRepository\AbstractBase;

/**
 * UsuarioSCPAEntityRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsuarioSCPARepository extends AbstractBase
{
}
